Document: piradio-3.13
Title: Debian piradio-3.13 Manual
Author: <insert document author here>
Abstract: This manual describes what piradio-3.13 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/piradio-3.13/piradio-3.13.sgml.gz

Format: postscript
Files: /usr/share/doc/piradio-3.13/piradio-3.13.ps.gz

Format: text
Files: /usr/share/doc/piradio-3.13/piradio-3.13.text.gz

Format: HTML
Index: /usr/share/doc/piradio-3.13/html/index.html
Files: /usr/share/doc/piradio-3.13/html/*.html
