#!/bin/sh
#
# Raspberry Pi Internet Radio Init script
# $Id: pifacercd,v 1.4 2016/01/03 09:25:59 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# This script controls the piface remote control daemon
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
#             The authors shall not be liable for any loss or damage however caused.
#
### BEGIN INIT INFO
# Provides:          pifacercd
# Should-Start:      
# Should-Stop:       
# Required-Start:    $remote_fs $syslog   
# Required-Stop:     $remote_fs $syslog 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry PiFace remote control daemon
# Description:       Start the PifFace Remote control daemon Daemon (pifacercd) service
### END INIT INFO

. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin

if [ -d /usr/share/radio ]; then
	DIR=/usr/share/radio
else
	DIR=/home/pi/radio
fi

NAME=remote_control.py
DESC="PiFice CAD remote control daemon"
DAEMON=${DIR}/${NAME}

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        ${DAEMON} start
        ;;
    stop)
        ${DAEMON} stop
        ;;
    status)
        ${DAEMON} status
	;;
    version)
        ${DAEMON} version
	;;
    restart)
        ${DAEMON} restart
        ;;
    flash)
        ${DAEMON} flash
        ;;
    force-reload)
        ${DAEMON} restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|flash|version}"
        exit 2
        ;;
esac
