#!/bin/sh
#
# Raspberry Pi Internet Radio Init script
# $Id: radiod,v 1.6 2016/04/02 08:59:31 bob Exp $
#
# Author : Bob Rathbone
# Site   : http://www.bobrathbone.com
#
# This script controls the radiod service
#
# License: GNU V3, See https://www.gnu.org/copyleft/gpl.html
#
# Disclaimer: Software is provided as is and absolutly no warranties are implied or given.
# The authors shall not be liable for any loss or damage however caused.
#
### BEGIN INIT INFO
# Provides:          radiod
# Should-Start:      
# Should-Stop:       
# Required-Start:    $remote_fs $syslog   
# Required-Stop:     $remote_fs $syslog 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry PI Radio Daemon
# Description:       Start the Radio Daemon (radiod) service
#                    for network access to the local audio queue.
### END INIT INFO

. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Change NAME parameter this next line to the version of the daemon you are using
# Choices are radiod.py, radio4.py, rradiod.py, rradio4.py or ada_radio.py
# No spaces around the = character

if [ -d /usr/share/radio ]; then
   DIR=/usr/share/radio
else
   DIR=/home/pi/radio
fi

NAME=radiod.py
DESC="PI Radio Daemon"
DAEMON=${DIR}/${NAME}

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        ${DAEMON} start
        ;;
    stop)
        ${DAEMON} stop
        ;;
    status)
        ${DAEMON} status
	;;
    version)
        ${DAEMON} version
	;;
    restart)
        ${DAEMON} restart
        ;;
    force-reload)
        ${DAEMON} restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status|version}"
        exit 2
        ;;
esac
